### ISSUE TITLE
Task 12 - Presentation video

### ISSUE THREAD

**Issue by sajudson** [sajudson/dataviz-project#1]
- [x] draft script (outline/readme)
- [x]  record video
- [x]  edit for content and time
- [x]  post to youtube
- [x]  add link to youtube to web page
- [x]  add link to visualization on youtube web page

**Comment by sajudson** [comment]
- [ ]  draft script
- [ ] record video
- [ ] edit for content and time
- [ ] post to youtube
- [ ] add link to youtube to web page

**Comment by apratt2003** [comment]
good break down of the presentation video.  I hope you don't mind me using the same format?!
